### ISSUE TITLE
the same color for ctrl+D - Add Selection To Next Find Match

### ISSUE THREAD

**Issue by palemajki** [azemoh/vscode-one-monokai#1]
when adding selection to next find match, highlight for not selected match is the same color as selected, so it is hard to differentiate.
**Now:** http://i.imgur.com/1kARBOB.jpg
**What it can look like:** http://i.imgur.com/AfRYwTb.jpg

Overall - thank you for your great work!

**Comment by azemoh** [comment]
Thanks, and thanks for pointing this out.
