### ISSUE TITLE
Whitespace dots match the color of the highlighted line

### ISSUE THREAD

**Issue by notgiorgi** [azemoh/vscode-one-monokai#11]
![image](https://user-images.githubusercontent.com/12987425/28513324-bbdcbb78-7066-11e7-846c-5fef16c2d3e2.png)

As you can see on the screenshot, on the first line whitespace dots are rendered and visible, but on the second line even though they're rendered, they're not visible because of background color.

**Comment by azemoh** [comment]
PR merged!
