### ISSUE TITLE
Unable to discern partial-term highlights

### ISSUE THREAD

**Issue by jtlapp** [azemoh/vscode-one-monokai#14]
When I highlight only part of a word, the entire word gets highlighted in addition to the part of the word that I highlighted, and the difference between the two highlights isn't significant enough for me to see. I find myself sometimes copying the wrong portion or repeatedly highlighting to make sure -- from memory -- that I got the right portion.

I find myself doing this with long names when I need to change the case of the first letter in a copy.

In this image, I've highlighted "roces" in the middle of the word "process" to demonstrate the issue. The outside 'p' and 's' are highlighted with 0x4A4B4D, while the "roces" is highlighted with 0x505256. That's too small a difference for me to see without having to mechanically scan my eyes across the word to find the change in color.

<img width="358" alt="screen shot 2017-09-18 at 1 49 21 pm" src="https://user-images.githubusercontent.com/138133/30559062-ff5fb29a-9c78-11e7-857e-08d715999dee.png">

This is my *only* issue with One Monokai, which I otherwise find perfect (and said so in my VSC review).

Why is the whole term being highlighted anyway? I'm not sure I've seen this behavior in an editor before. I'm new to VSC.

**Comment by azemoh** [comment]
Thanks, @jtlapp for the review and thanks for raising this here. I'll try to have it fixed, however, I'll be happy to take contributions.

**Comment by jtlapp** [comment]
I'm now seeing that my common scenarios are highlighting the first letter to change it, and highlighting prefixes and suffixes to change them.

I also see that the whole term gets highlighted throughout the file, which helps to elucidate why the term gets highlighted at all.

I'm not sure what colors would work. You have such a nice color balance. Even the highlight is pleasant to look at. What about underlining the term throughout the file, instead of changing its background color? I'm guessing the underline color would need to be bright to make them noticeable, given that they get highlighted randomly throughout.

**Comment by jtlapp** [comment]
I'm investigating this again. The problem is more extensive than I thought. The two colors shown depend on the type of term being highlighted. The contrast varies from term to term.

I looked at how numerous other color themes handle this. Most of the dark background themes have this problem, and most of the light background themes do not. There are exceptions.

The High Contrast theme completely solved the problem, but with a negative consequence. It outlines search terms in orange dashes. That looks fine in the code, but it may be that the same control governs the highlighting of menu items, making it a poor choice. See attached.

Since some of the dark themes do show highlights well, I'll see if I can find a fix
<img width="640" alt="screen shot 2017-09-26 at 9 18 15 pm" src="https://user-images.githubusercontent.com/138133/30892913-e107e19e-a300-11e7-9253-2228c0b62c92.png">
 for One Monokai.

**Comment by jtlapp** [comment]
I've figured out what the problem is. The best solution seems to be to make highlighted text completely black (#000000) or nearly so.

VSC automatically computes the highlight background color when it is also trying to give a term a color according to its function. The highlight background colors therefore vary by the kind of term being highlighted. The color is computed by combining the terms functional color with the color chosen for `editor.selectionBackground` -- the normal selection background color.

The highlight color therefore needs to contrast well with the background color of the term. Because all the term background colors are mid-range brightness, the highlight color would need to be either pretty bright or pretty dark. Moreover, because the background colors tend to have a bluish hue, we get better contrast from a highlight that is opposite the color wheel, like yellow or pinkish.

But the foreground colors of the characters are bright, so the brighter the highlight color, the harder the text is to read. Darker background highlight creates a stronger contrast, contrary to the otherwise soft nature of the color theme, but at least the text is clearly legible.

It is also an option to set either the color or the border of the term that is partially highlighted. Setting the color causes the partial highlight to be entirely obliterated by that color -- it becomes impossible to highlight portions of words! I saw this happening in some other color themes and now know why. Setting the border changes the border color of all active elements throughout the workspace, as you saw in my previous comment, and VSC decides when to make it solid, dotted, or dashed. I find that unpleasant.

Here are some examples. The first sets the selection color to `#000000`:

<img width="426" alt="screen shot 2017-09-26 at 10 49 59 pm" src="https://user-images.githubusercontent.com/138133/30895433-ce6ba606-a30f-11e7-9f73-acd98fd52ceb.png">

<img width="510" alt="screen shot 2017-09-26 at 10 49 47 pm" src="https://user-images.githubusercontent.com/138133/30895441-d7e5c6e4-a30f-11e7-958e-460c2115e8df.png">

The second sets it to `#040404`, which may be the limit of reducing the contrast for multi-line text selections while still producing a discernible intra-term selection:

<img width="464" alt="screen shot 2017-09-26 at 11 01 08 pm" src="https://user-images.githubusercontent.com/138133/30895462-03b73f00-a310-11e7-998c-b1b2adecc0c8.png">

<img width="527" alt="screen shot 2017-09-26 at 11 00 55 pm" src="https://user-images.githubusercontent.com/138133/30895464-08fdac24-a310-11e7-93d1-7d3fbe0ab8f8.png">

The last shows what happens when we opt to make the selection bright enough to make a difference intra-term. This selection color is `#927C9B`:

<img width="422" alt="screen shot 2017-09-26 at 10 50 30 pm" src="https://user-images.githubusercontent.com/138133/30895492-38e8b730-a310-11e7-96ca-f960bd20b876.png">

<img width="516" alt="screen shot 2017-09-26 at 10 50 21 pm" src="https://user-images.githubusercontent.com/138133/30895496-3dd44c14-a310-11e7-81f7-3b3f6edbd8fe.png">

The bright color may look nice here, but it produces some hard-to-read highlights in other places:

<img width="492" alt="screen shot 2017-09-26 at 11 13 53 pm" src="https://user-images.githubusercontent.com/138133/30895528-63fa3caa-a310-11e7-90ba-2ce9426795a9.png">

So what do you think about switching to a black highlight? I'll play with it for a while to see if any problems surface.

**Comment by jtlapp** [comment]
For kicks, I decided to see how dark I could make the pink highlight and still end up with discernible intra-term highlights. The limit seems to be around `#83738d`.

<img width="491" alt="screen shot 2017-09-26 at 11 25 33 pm" src="https://user-images.githubusercontent.com/138133/30895800-28bbd444-a312-11e7-982e-9f33bea7f394.png">

<img width="522" alt="screen shot 2017-09-26 at 11 25 43 pm" src="https://user-images.githubusercontent.com/138133/30895802-2ef9279e-a312-11e7-8ddd-cc6bf505e7f7.png">

**Comment by jtlapp** [comment]
I guess the main disadvantage of the black highlight is that it doesn't look like a highlight -- it's a lowdark.

**Comment by jtlapp** [comment]
Here's a bluish highlight that actually looks nice. It's `#74738D`. So much for my color wheel theory. I've been playing around with the hue, and so far this (and other pinks) are the only ones that look nice.

<img width="441" alt="screen shot 2017-09-27 at 8 11 12 am" src="https://user-images.githubusercontent.com/138133/30915349-24d1d668-a35c-11e7-9aad-bec6d6fc4bef.png">

<img width="516" alt="screen shot 2017-09-27 at 8 11 27 am" src="https://user-images.githubusercontent.com/138133/30915352-2aa0f7d6-a35c-11e7-9df4-8241d371357a.png">

<img width="447" alt="screen shot 2017-09-27 at 8 14 39 am" src="https://user-images.githubusercontent.com/138133/30915358-304ae19c-a35c-11e7-9151-77bebd802db1.png">

Here's something greyish-pink (`#8a71871):

<img width="485" alt="screen shot 2017-09-27 at 8 28 17 am" src="https://user-images.githubusercontent.com/138133/30915975-e1ca3ae8-a35d-11e7-80f2-d61a0b00efa5.png">

<img width="512" alt="screen shot 2017-09-27 at 8 25 59 am" src="https://user-images.githubusercontent.com/138133/30915990-e756e010-a35d-11e7-9690-9607dbec7265.png">

<img width="452" alt="screen shot 2017-09-27 at 8 28 26 am" src="https://user-images.githubusercontent.com/138133/30916004-ed197972-a35d-11e7-88ea-bd20679a7247.png">

Here's a more pure pink, as dark as I'm willing to make it and keep intra-term highlights discernible (`#8a6e89`):

<img width="488" alt="screen shot 2017-09-27 at 8 32 22 am" src="https://user-images.githubusercontent.com/138133/30916247-94b20212-a35e-11e7-9bd1-778c13455e43.png">

<img width="515" alt="screen shot 2017-09-27 at 8 32 30 am" src="https://user-images.githubusercontent.com/138133/30916254-992b4f60-a35e-11e7-9e20-9f988167e261.png">

<img width="414" alt="screen shot 2017-09-27 at 8 32 39 am" src="https://user-images.githubusercontent.com/138133/30916263-9ced69c6-a35e-11e7-8d13-0cfcbdcf165a.png">

**Comment by jtlapp** [comment]
And here's a pure grey (`#707070`). Okay, I'm going to do something else now...

<img width="442" alt="screen shot 2017-09-27 at 8 44 21 am" src="https://user-images.githubusercontent.com/138133/30916902-2cf564d2-a360-11e7-9240-374e1d0581c9.png">

<img width="507" alt="screen shot 2017-09-27 at 8 44 31 am" src="https://user-images.githubusercontent.com/138133/30916903-31bd2a90-a360-11e7-888a-0ce6db1b5a0e.png">

<img width="456" alt="screen shot 2017-09-27 at 8 44 40 am" src="https://user-images.githubusercontent.com/138133/30916907-36ac1430-a360-11e7-9445-81c9f3b035f4.png">

**Comment by jtlapp** [comment]
Ah poo. I just realized that half of the above screenshots are of the highlights in a de-active state. When you switch to another editor window, VSC changes the brightness. I guess you'll need to play around for yourself to get a sense of things.

I'll try again, just a quick review. Here are the highlights that allow for discernible intra-term highlighting. The non-black highlights seem to trade visibility of intra-term highlights for readability of multi-line highlights. My preference is for a brighter highlight than the current one, in any case.

<img width="517" alt="screen shot 2017-09-27 at 9 02 11 am" src="https://user-images.githubusercontent.com/138133/30918184-6a52eafe-a363-11e7-9f4b-ce51261caeb4.png">

<img width="507" alt="screen shot 2017-09-27 at 9 02 31 am" src="https://user-images.githubusercontent.com/138133/30918188-6a53ae44-a363-11e7-8292-688082667a1d.png">

<img width="504" alt="screen shot 2017-09-27 at 9 02 51 am" src="https://user-images.githubusercontent.com/138133/30918189-6a53c7a8-a363-11e7-8082-33b040d1a4a4.png">

<img width="510" alt="screen shot 2017-09-27 at 9 03 12 am" src="https://user-images.githubusercontent.com/138133/30918186-6a535d9a-a363-11e7-9d02-4f1d2c665a82.png">

<img width="513" alt="screen shot 2017-09-27 at 9 03 31 am" src="https://user-images.githubusercontent.com/138133/30918185-6a53084a-a363-11e7-876c-323543c7e73c.png">

<img width="508" alt="screen shot 2017-09-27 at 9 03 48 am" src="https://user-images.githubusercontent.com/138133/30918187-6a537fdc-a363-11e7-994a-7b0ccc6ae57a.png">

<img width="522" alt="screen shot 2017-09-27 at 9 04 34 am" src="https://user-images.githubusercontent.com/138133/30918190-6a70437e-a363-11e7-9f19-69b796e29ff3.png">

<img width="498" alt="screen shot 2017-09-27 at 9 04 56 am" src="https://user-images.githubusercontent.com/138133/30918191-6a7094b4-a363-11e7-92ec-fa113e5f686b.png">

**Comment by jtlapp** [comment]
Well, highlighting in with the brighter color makes comments nearly unreadable. I think black highlighting is the only way to make intra-term highlights discernible.

<img width="595" alt="screen shot 2017-09-29 at 9 27 39 am" src="https://user-images.githubusercontent.com/138133/31020655-38a52f2a-a4f9-11e7-859b-8cd358e7b2bd.png">

Black highlighting has the additional benefit of making all the highlighted text easy to read.

Also, I find myself straining to read comments on the normal background and would prefer to bump their brightness up just a tad.

**Comment by jtlapp** [comment]
We can take a little bit of the edge off of the black highlight, as here with `#020004`. Unfortunately, we can't get much brighter without losing the ability to see intra-term highlights.

<img width="489" alt="screen shot 2017-09-29 at 10 17 09 am" src="https://user-images.githubusercontent.com/138133/31022824-9f7a7722-a4ff-11e7-95ba-b7ba25d4f194.png">

<img width="518" alt="screen shot 2017-09-29 at 10 17 29 am" src="https://user-images.githubusercontent.com/138133/31022829-a461526a-a4ff-11e7-904b-5f9ae6eaaf37.png">

<img width="446" alt="screen shot 2017-09-29 at 10 17 54 am" src="https://user-images.githubusercontent.com/138133/31022846-aac20924-a4ff-11e7-8a00-028e64faba08.png">

**Comment by jtlapp** [comment]
Shall I create a PR to change the selection background color to `#020004`, per my previous comment?

**Comment by jtlapp** [comment]
Aaaaagh! Highlighting is just plain broken in VSC. The black highlighting fixed the above-mentioned problems, but created new problems. Here's what happens when I double-click on a word under various highlight colors:

The original highlight color `#3E4451`:
<img width="250" alt="screen shot 2017-09-29 at 12 36 16 pm" src="https://user-images.githubusercontent.com/138133/31028333-143edf22-a513-11e7-9f74-e4d8f56417b8.png">

The nice bright blue highlight `#74738D`:
<img width="268" alt="screen shot 2017-09-29 at 12 35 15 pm" src="https://user-images.githubusercontent.com/138133/31028355-2e290200-a513-11e7-9564-684492e02885.png">

The new nearly-black highlight `#020004`:
<img width="251" alt="screen shot 2017-09-29 at 12 34 54 pm" src="https://user-images.githubusercontent.com/138133/31028371-409a6320-a513-11e7-8dd3-5fced9d677c3.png">

Notice in the latter that you can't even tell which identifier I highlighted!

So I have not yet found any highlighting color that both makes intra-term highlights discernible and works with the rest of One Monokai.

**Comment by jtlapp** [comment]
Fortunately, VSC makes it easy for us to override the default highlighting. Choose the color you want (such as from the above possibilities -- none are perfect), and it to the settings file:

```
    "workbench.colorCustomizations": {
        "editor.selectionBackground": "#3E4451" //original
        //"editor.selectionBackground": "#74738D" //bluish
        //"editor.selectionBackground": "#83738D" //pinkish
        //"editor.selectionBackground": "#000000" //black
        //"editor.selectionBackground": "#020004" //nearly black
    }
```

I'm closing this issue for being impossible to address.
