### ISSUE TITLE
Increase comment brightness a tad

### ISSUE THREAD

**Issue by jtlapp** [azemoh/vscode-one-monokai#16]
I find myself straining to read my longer comments. Maybe it's because I'm middle-aged now. In any case, I propose increasing comment brightness from `#5c6370` to `#676f7d`.

Comments are currently `#5c6370`:
<img width="568" alt="screen shot 2017-09-29 at 10 23 07 am" src="https://user-images.githubusercontent.com/138133/31023270-f535571c-a500-11e7-97db-0efebd8d3a98.png">

I propose providing a PR to change comments to `#676f7d`:
<img width="570" alt="screen shot 2017-09-29 at 10 24 38 am" src="https://user-images.githubusercontent.com/138133/31023300-08c085c2-a501-11e7-87d7-c54df4ab44d5.png">

**Comment by Geobert** [comment]
I agree, this PR should be merge, it's the only issue I have with this theme

**Comment by azemoh** [comment]
I agree as well. Thanks for raising a PR for this @jtlapp. I'll have it published ASAP!
