### ISSUE TITLE
Embedded code in strings (for ruby) is not highlighted

### ISSUE THREAD

**Issue by shir** [azemoh/vscode-one-monokai#19]
Thanks for good color theme. But I have a small issue for Ruby language. I see on screenshot in README file that embedded code is highlighted:

<img width="375" alt="screenshot-v0 2 0" src="https://user-images.githubusercontent.com/229417/33482358-b32d0baa-d6a9-11e7-8744-4b37a1b9e9c2.png">

But in real usage it's not highlighted separately and looks just like a whole string:

<img width="439" alt="screen shot 2017-12-01 at 15 07 19" src="https://user-images.githubusercontent.com/229417/33482376-cb961a2e-d6a9-11e7-9936-666b7e3b8c1a.png">

Looks like something become broken.

**Comment by shir** [comment]
Don't know if solution is right but next settings helped:
```json
    "editor.tokenColorCustomizations": {
        "textMateRules": [
            {
                "scope": "punctuation.section.embedded",
                "settings": {
                    "foreground": "#c678dd"
                }
            },
            {
                "scope": "variable.other",
                "settings": {
                    "foreground": "#bbbbbb"
                }
            }
        ]
    }
```

**Comment by sluchznak** [comment]
![2017-12-13_11-51-19](https://user-images.githubusercontent.com/4091442/33923547-fb849ff2-dffb-11e7-8a32-00a6a2df2fc3.png)

Php same
