### ISSUE TITLE
Suggestion: Update "editorUnnecessary.foreground" to contrast with base text.

### ISSUE THREAD

**Issue by paterasMSFT** [azemoh/vscode-one-monokai#22]
VS Code just launched unused import and variable highlighting. Unfortunately, One Monokia's base text color is the exact same color that VS Code now uses for unused variables and imports. Updating this setting will allow give some contrast:

>"editorUnnecessary.foreground": "#ffff00"

Thanks for this great theme!

**Comment by azemoh** [comment]
Thanks for reporting this @paterasMSFT. It appears the key has since been deprecated in favour of `editorUnnecessaryCode.opacity`.

> "editorUnnecessaryCode.opacity": "#000000c0"
