### ISSUE TITLE
Typescript Template Literals don't highlight

### ISSUE THREAD

**Issue by IronSean** [azemoh/vscode-one-monokai#25]
#6 is still an ongoing issue for .ts and .tsx files. Could the template literal handling be added to them as well?

**Comment by brunolemos** [comment]
Came here to report the same thing:

![image](https://user-images.githubusercontent.com/619186/60760479-5190b300-a00c-11e9-81e8-7f8e1cb385e4.png)

Should work on `.js`, `.ts` and `.tsx`.

**Comment by ulshv** [comment]
@notgiorgi, @azemoh 

I see you merged this PR https://github.com/azemoh/vscode-one-monokai/pull/8 to fix it, but it didn't help.. Can you please check what is the problem (I tried to hack with configs by myself but with no success). 

This is the only issue I have with One Monokai theme, and don't want to switch to another one because it is the best! ;)

**Comment by azemoh** [comment]
@IronSean, @brunolemos, @ulshv 

![Screen Shot 2019-09-28 at 8 48 04 PM](https://user-images.githubusercontent.com/11008869/65821719-53e06300-e231-11e9-830f-b57cb154ca11.png)

I checked and this looks good on my end _(Default VS Code TypeScript extension)_. Could it be an issue where your Typescript extension does not define the theme scopes?

**Comment by brunolemos** [comment]
What do you mean? This only happens when I use the `One Monokai` theme, all other theme works as expected.

**Comment by brunolemos** [comment]
It seems this only happens if you use for a variable name without nested properties:

![image](https://user-images.githubusercontent.com/619186/65823129-0d860680-e227-11e9-8f6a-f6466c6a611d.png)

**Comment by azemoh** [comment]
@brunolemos I just published an update. Could you try it and let me know if this is resolved?

**Comment by ulshv** [comment]
@azemoh just installed the latest version - it fixed now! Thanks! ;)
