### ISSUE TITLE
Hello, what is this font?

### ISSUE THREAD

**Issue by liushuhui** [azemoh/vscode-one-monokai#27]
Hello, what is this font?

**Comment by Ultra-Doggo** [comment]
Make that a 3rd, I'm also curious what font is used in the screenshots!

**Comment by rolivegab** [comment]
Me too

**Comment by azemoh** [comment]
Hey all. I think it is [**Roboto Mono**](https://fonts.google.com/specimen/Roboto+Mono). That was a long time ago.

**Comment by azemoh** [comment]
@here I've been looking for this as well and I finally found it. https://fonts.google.com/specimen/Inconsolata
