### ISSUE TITLE
How to I disable italic on comments?

### ISSUE THREAD

**Issue by NDelt** [azemoh/vscode-one-monokai#29]
![cap3](https://user-images.githubusercontent.com/46282492/53241241-74b56880-36e4-11e9-834f-5bb5a74c2ba4.PNG)
I want to disable italic on comments in every file types.
How to I configure it?

**Comment by alekseyt** [comment]
```diff
index cf0429c..4b608e5 100644
--- a/themes/OneMonokai-color-theme.json
+++ b/themes/OneMonokai-color-theme.json
@@ -22,8 +22,7 @@
         "string.comment"
       ],
       "settings": {
-        "foreground": "#676f7d",
-        "fontStyle": "italic"
+        "foreground": "#676f7d"
       }
     },
     {
```

Hope this helps.

It would be nice to disable italic in comments indeed. Italic breaks sketches (and formatting in general) in comments.

**Comment by azemoh** [comment]
That is a good point @alekseyt. It was just a personal choice. I am open to disabling italic on comments.
