### ISSUE TITLE
Custom Element tags are shown with two different colors.

### ISSUE THREAD

**Issue by boyum** [azemoh/vscode-one-monokai#3]
When using Custom Elements (or any framework that implements similar behaviour), it is highly recommended ([even required in some cases](https://developers.google.com/web/fundamentals/getting-started/primers/customelements)) to use dash (-) in tag names. Ex: `<my-button></my-button>`.

VSCode One Monokai renders the first part in the regular red, but the rest in the attributes' green.

I might look into this, but have no experience whatsoever in creating custom themes. 

Hope you'll find a solution for this. Love the theme, keep up the good work!

**Comment by azemoh** [comment]
Thanks, @boyum. I'll look into this.

**Comment by azemoh** [comment]
Hey @boyum, thanks for raising this issue. It has been fixed with VSCode updated JS and JSX grammar.
