### ISSUE TITLE
Right side of new VS Code logo is almost invisible

### ISSUE THREAD

**Issue by SamueleDassatti** [azemoh/vscode-one-monokai#32]
![image](https://user-images.githubusercontent.com/23523551/58424744-633f7c00-8098-11e9-9586-d54c3ae4e84f.png)

The right-hand side of the new Visual Studio Code logo is so similar to the One Monokai background that it's almost invisible.

**Comment by Hezkore** [comment]
I spent a good 10 minutes staring to the left side of the logo, wondering what you were talking about.
I had to pull it into Photoshop and adjust the levels to notice that the **_right_** side of the logo is missing.

Here's the adjusted image:
![right](https://user-images.githubusercontent.com/1727541/59569022-1f7ed780-9084-11e9-9c67-43691ce1adac.png)

**Comment by SamueleDassatti** [comment]
My bad, I really don't know why I wrote left instead of right.

**Comment by azemoh** [comment]
Apologies it took forever for me to get to this. I wouldn't want to mess with the background color as a lot of people like that it is easy on the eye. However, VS Code has since changed the welcome screen (removing the logo), so this is no longer an issue.
