### ISSUE TITLE
Common Markdown Syntax Highlighting is Unsupported

### ISSUE THREAD

**Issue by MasterKale** [azemoh/vscode-one-monokai#4]
Markdown syntax highlighting is severely muted with this theme. A lot of common markdown elements receive no highlighting:

<img width="439" alt="screen shot 2017-02-15 at 7 34 32 am" src="https://cloud.githubusercontent.com/assets/5166470/22981433/3f291ed8-f351-11e6-99b3-c75e2761b034.png">

Compare this same document using the built-in *Monokai* theme:

<img width="404" alt="screen shot 2017-02-15 at 7 35 20 am" src="https://cloud.githubusercontent.com/assets/5166470/22981487/6052d4a0-f351-11e6-9604-4ca26fe00a02.png">

Would you consider adding in more support for Markdown syntax highlighting?

**Comment by azemoh** [comment]
Markdown support is now available, added by @davvidbaker 🎉🎉
