### ISSUE TITLE
Workbench theming

### ISSUE THREAD

**Issue by nwaywood** [azemoh/vscode-one-monokai#5]
The April release of VS Code added [workbench theming](https://github.com/Microsoft/vscode-docs/blob/vnext/release-notes/v1_12.md#workbench-theming)

It would be amazing if you could update this theme to include workbench theming!

**Comment by azemoh** [comment]
Thanks for the reminder, I'll add this as soon as I can.

**Comment by azemoh** [comment]
Added [here](https://github.com/azemoh/vscode-one-monokai/commit/8e4ee8cd3d6109e84b8b2cc76134a8d0f8ac5433)
