### ISSUE TITLE
Wrong color in C# constructions

### ISSUE THREAD

**Issue by KholkinDmitrii** [azemoh/vscode-one-monokai#55]
Hi. I love this theme! I tried all themes in the market, but this theme is the best! But I have a problem. Some constructions break the color in the code. This example shows the problem with "await" before "foreach". Look at the colors of "using", "var", "try", "catch" etc. The second picture has the correct colors. Can you solve this problem, please?
<img width="698" alt="Screenshot 2024-08-12 at 22 12 40" src="https://github.com/user-attachments/assets/9bcfe1eb-b7b1-4209-afb1-2c2e6fb2db90">
<img width="698" alt="Screenshot 2024-08-12 at 22 12 48" src="https://github.com/user-attachments/assets/a3f6f8f9-c76b-4379-979f-b2e0cc4d5986">

**Comment by DmitriiKholkin** [comment]
This is a dead project.
