### ISSUE TITLE
Variables in javascript string literals should be a different colour

### ISSUE THREAD

**Issue by bhaesler** [azemoh/vscode-one-monokai#6]
Example:

**One Monokai**
![image](https://cloud.githubusercontent.com/assets/14072487/25928532/11eb2d12-3640-11e7-932b-bdd261274e55.png)

**One Dark Pro** 
![image](https://cloud.githubusercontent.com/assets/14072487/25928546/234f5a6a-3640-11e7-9aab-b3fc8801eeee.png)

**Comment by azemoh** [comment]
Thanks for raising this 👍

**Comment by notgiorgi** [comment]
I want to send PR for this, where does one find docs for VSCode theming?

**Comment by azemoh** [comment]
Thanks @notgiorgi. VSCode uses Textmate/Sublime Text theming. Here's the [docs](https://www.sublimetext.com/docs/3/scope_naming.html)
Reference [here](https://code.visualstudio.com/docs/extensions/themes-snippets-colorizers#_adding-a-new-theme)

**Comment by notgiorgi** [comment]
How do I convert this to tmtheme?
```
{
	"name": "js template-expression",
	"scope": "punctuation.definition.template-expression.begin.js,punctuation.definition.template-expression.end.js,punctuation.definition.template-expression.begin.ts,punctuation.definition.template-expression.end.ts",
	"settings": {
		"foreground": "#e06c75"
	}
},
{
	"name": "TemplateString",
	"scope": "string.template.js",
	"settings": {
		"foreground": "#8bb271"
	}
},
{
	"name": "TemplateString",
	"scope": "meta.template.expression.js",
	"settings": {
		"foreground": "#e06c75"
	}
},
```

**Comment by azemoh** [comment]
I am going to convert the theme to use this new syntax so you don't have to. I'll @ you when I do.

**Comment by azemoh** [comment]
Done @notgiorgi. Thanks, you can add it now.
